#!/usr/bin/env bash
# install nginx and configure it.
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/error_404.html
sed -i '25i\    error_page 404 /error_404.html;' /etc/nginx/sites-available/default
service nginx start
