#!/usr/bin/env bash
# Bash script that install and configure HAproxy on your lb-01 server.

apt-get update
apt-get install -y haproxy

echo "ENABLED=1" >> /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.khaled_original}
touch /etc/haproxy/haproxy.cfg

printf %s "
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers
    
backend webservers
    mode http
    server 530926-web-01 54.237.48.43:80 check
    server 530926-web-02 35.175.132.199:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start

