#!/usr/bin/env bash
# Check if the password argument is provided
if [ -z "$1" ]; then
    echo "Usage: $0 <mysql_password>"
    exit 1
fi

# Get the current date
current_date=$(date +'%d-%m-%Y')

# MySQL dump file name
dump_file="backup.sql"

# Compressed archive name
archive_name="$current_date.tar.gz"

# MySQL dump command
mysqldump --user=root --all-databases > "$dump_file"

# Create a tar.gz archive
tar -czf "$archive_name" "$dump_file"

echo $dump_file
