#!/usr/bin/env bash
# Using a while loop to display "Best School" 10 times

counter=0
while [ $counter -ne 10 ]
do
    echo "Best School"
    (( counter++ ))
    if [ $counter -eq 9 ]
    then
		echo "Hi"
    fi
done

