#!/usr/bin/env bash
# task 6

counter=0
while [ $counter -ne 20 ]
do
    (( counter++ ))
    echo "$counter"
    case $counter in
     "4") echo "bad luck from China";;
     "9") echo "bad luck from Japan";;
     "17") echo "bad luck from Italy";;
    esac
done

